# Generated by Django 2.2.5 on 2020-07-01 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20200701_1706'),
        ('reservations', '0002_auto_20200701_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='rooms.Room'),
            preserve_default=False,
        ),
    ]
